# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [MIA, Parker]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username vodoo.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username King Kong
issuehunt: # Replace with a single IssueHunt username Lincoln
otechie: # Replace with a single Otechie username Oprah
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://sans.org','https://skills.com','https://meetup.com','https://consumercellular.com','https://marchofdimes.org',https://thetruth.org','https://cash.app/$mouse3687','https://lionstudios.cc']
