name: Test POST
on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Execute a dummy request
        id: request
        uses: ./
        with:
          url: 'https://jsonplaceholder.typicode.com/todos'
          method: post
          data: '{ "title": "dummy-todo", "userId": 1, "completed": false }'
      - name: Print the response status
        run: echo ${{ steps.request.outputs.status }}
        shell: bash
      - name: Print the response
        run: echo ${{ steps.request.outputs.response }}
        shell: bash
