name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Execute a dummy query
        id: query
        uses: ./
        with:
          query: |
            some
            multiline
            query
      - name: Print the query result
        run: echo ${{ steps.query.outputs.status }}
        run: echo ${{ steps.query.outputs.result }}
